### ISSUE TITLE
Add pics to team camera

### ISSUE THREAD

**Issue by qqumn** [activebridge/activebridge#230]
Upload new cool pics to our camera.

Requirements:
- width >=  700px
- landscape orientation
- compressed by [https://tinypng.com/](https://tinypng.com/)

Just add link into `locales/en.yml`
```
  team:
    title: Team
    photos:
      - http://i.imgur.com/HtFZC6N.jpg
      - http://i.imgur.com/5CTZocf.jpg
```
